services:
  - type: web
    name: code-reviewer-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
    healthCheckPath: /